server:
  port: 8080

spring:
  datasource:
    write:
      username: pingcai
      password: 314115
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://95.163.198.151:3306/java_staging?useUnicode=true&characterEncoding=utf-8&useSSL=false
      type: com.zaxxer.hikari.HikariDataSource
    read:
      username: pingcai
      password: 314115
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://95.163.198.151:3306/java_staging?useUnicode=true&characterEncoding=utf-8&useSSL=false
      type: com.zaxxer.hikari.HikariDataSource